# Generated by Django 3.2.4 on 2023-08-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='url')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='color')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='url')),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='my_calendar.analytics')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('instruction', models.TextField(blank=True, null=True, verbose_name='description')),
                ('visible', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('start_datetime', models.DateTimeField(auto_now_add=True, verbose_name='start_datetime')),
                ('end_datetime', models.DateTimeField(auto_now_add=True, verbose_name='end_datetime')),
                ('last_update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='last_update_datetime')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='my_calendar.bank')),
                ('event_analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventAnalytics', to='my_calendar.eventanalytics')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='my_calendar.status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='my_calendar.type')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
