# Generated by Django 3.2.4 on 2023-08-24 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20230824_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_tg_admin_mode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unverified_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code_expired_at',
        ),
        migrations.CreateModel(
            name='UserInteresting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
